<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ecommerce - Your Online Shopping Destination</title>
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
</head>
<body>
    <!-- Header -->
    <header>
        <div class="header-top">
            <a href="#" class="logo">Ecommerce</a>
            <div class="header-center">
                <div class="search-bar">
                    <input type="text" placeholder="Search for any product or brand">
                    <button>Search</button>
                </div>
            </div>
            <div class="header-right">
                <a href="#" class="header-icon">
                    <span class="icon">🌐</span>
                    <span>English</span>
                </a>
                <a href="#" class="header-icon">
                    <span class="icon">❤️</span>
                    <span>Wishlist</span>
                </a>
                <a href="#" class="header-icon">
                    <span class="icon">👤</span>
                    <span>Sign In</span>
                </a>
                <a href="#" class="header-icon">
                    <span class="icon">🛒</span>
                    <span>Cart</span>
                </a>
            </div>
        </div>

        <!-- Navigation -->
        <nav class="nav-categories">
            <a href="#" class="active">All Categories</a>
            <a href="#">Electronics</a>
            <a href="#">Fashion</a>
            <a href="#">Home & Decor</a>
            <a href="#">Health & Beauty</a>
            <a href="#">Sports</a>
            <a href="#">Books</a>
            <a href="#">Pharmacy</a>
            <a href="#">Groceries</a>
            <a href="#">Luxury Items</a>
        </nav>
    </header>

    <!-- Main Container -->
    <div class="container">
        <!-- Carousel -->
        <div class="carousel">
            <div class="carousel-container" id="carouselContainer">
                <div class="carousel-item">
                    <div class="carousel-slide">
                        <h2>iPhone 16 Pro Max</h2>
                        <p>From $50,769*</p>
                        <p>All-day, all-night battery. Supersmart. Impossibly thin.</p>
                        <a href="#" class="btn">Shop Now</a>
                    </div>
                    <div class="carousel-slide" style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); display: flex; align-items: center; justify-content: center;">
                        📱
                    </div>
                </div>
            </div>
            <button class="carousel-nav prev" onclick="moveCarousel(-1)">❮</button>
            <button class="carousel-nav next" onclick="moveCarousel(1)">❯</button>
            <div class="carousel-controls">
                <span class="carousel-dot active" onclick="currentSlide(0)"></span>
                <span class="carousel-dot" onclick="currentSlide(1)"></span>
                <span class="carousel-dot" onclick="currentSlide(2)"></span>
            </div>
        </div>

        <!-- Explore Categories -->
        <div class="section-header">
            <h3>Explore Popular Categories</h3>
            <a href="#" class="view-all">View All ></a>
        </div>
        <div class="categories-grid">
            <div class="category-card">
                <div class="category-icon">🎧</div>
                <p>Electronics</p>
            </div>
            <div class="category-card">
                <div class="category-icon">👗</div>
                <p>Fashion</p>
            </div>
            <div class="category-card">
                <div class="category-icon">💄</div>
                <p>Luxury</p>
            </div>
            <div class="category-card">
                <div class="category-icon">🪑</div>
                <p>Home Decor</p>
            </div>
            <div class="category-card">
                <div class="category-icon">💊</div>
                <p>Health & Beauty</p>
            </div>
            <div class="category-card">
                <div class="category-icon">🍎</div>
                <p>Groceries</p>
            </div>
            <div class="category-card">
                <div class="category-icon">👟</div>
                <p>Sneakers</p>
            </div>
        </div>

        <!-- Today's Best Deals -->
        <div class="section-header">
            <h3>Todays Best Deals For You!</h3>
            <a href="#" class="view-all">View All ></a>
        </div>
        <div class="products-grid" id="productsGrid">
            <!-- Products will be generated by JavaScript -->
        </div>

        <!-- Featured Banners -->
        <div class="banners-grid">
            <div class="banner banner-1">
                <h3>Fresh & Healthy Vegetables</h3>
                <p>Get up to 50% off on organic produce</p>
                <a href="#" class="btn">Shop Now</a>
            </div>
            <div class="banner banner-2">
                <h3>Samsung Galaxy S24 FE</h3>
                <p>Experience AI at home</p>
                <a href="#" class="btn">Shop Now</a>
            </div>
            <div class="banner banner-3">
                <h3>Special Offers</h3>
                <p>Top deals from the best brands</p>
                <a href="#" class="btn">Shop Now</a>
            </div>
        </div>

        <!-- Winter Wear Sale -->
        <div class="section-header">
            <h3>60% Off Or More On Winter-Wear</h3>
            <a href="#" class="view-all">View All ></a>
        </div>
        <div class="products-grid" id="winterWearGrid">
            <!-- Winter products will be generated by JavaScript -->
        </div>

        <!-- Top Deals Electronics -->
        <div class="section-header">
            <h3>Top Deals in Electronics</h3>
            <a href="#" class="view-all">View All ></a>
        </div>
        <div class="products-grid" id="electronicsGrid">
            <!-- Electronics products will be generated by JavaScript -->
        </div>

        <!-- Best Sellers Beauty & Health -->
        <div class="section-header">
            <h3>Best Sellers in Beauty & Health</h3>
            <a href="#" class="view-all">View All ></a>
        </div>
        <div class="products-grid" id="beautyHealthGrid">
            <!-- Beauty & Health products will be generated by JavaScript -->
        </div>
    </div>

    <!-- Footer -->
    <footer>
        <div class="footer-content">
            <div class="footer-section">
                <h4>About Us</h4>
                <a href="#">About emox</a>
                <a href="#">Careers</a>
                <a href="#">Blog</a>
                <a href="#">Press</a>
            </div>
            <div class="footer-section">
                <h4>Help & Support</h4>
                <a href="#">Contact Us</a>
                <a href="#">FAQ</a>
                <a href="#">Shipping Info</a>
                <a href="#">Returns</a>
            </div>
            <div class="footer-section">
                <h4>Policies</h4>
                <a href="#">Privacy Policy</a>
                <a href="#">Terms & Conditions</a>
                <a href="#">Cookie Policy</a>
                <a href="#">Security</a>
            </div>
            <div class="footer-section">
                <h4>Follow Us</h4>
                <a href="#">Facebook</a>
                <a href="#">Instagram</a>
                <a href="#">Twitter</a>
                <a href="#">YouTube</a>
            </div>
        </div>
        <div class="footer-bottom">
            <p>&copy; 2024 emox. All rights reserved.</p>
        </div>
    </footer>

    <script src="{{ url('js/app.js') }}"></script>
</body>
</html>
